### ISSUE TITLE
How to use air32f103cbt6 at 216MHz

### ISSUE THREAD

**Issue by NgoHungCuong** [openLuat/luatos-soc-air32f103#1]
How to use air32f103cbt6 at 216MHz

**Comment by chenxuuu** [comment]
参考demo目录里的RCC工程

**Comment by NgoHungCuong** [comment]
Air32f103cbt6 can not run at 216mhz

**Comment by chenxuuu** [comment]
air32全系列都能在216MHz运行

**Comment by NgoHungCuong** [comment]
Can not, I have tested. It works at 72MHz, and can not works at 216MHz.
Select 72MHz, all well, but select 216MHz, can not run.
Led is not blinking
![image](https://user-images.githubusercontent.com/17018444/208839129-8e8afe2a-8196-434a-81f8-8adc720ee86a.png)
![image](https://user-images.githubusercontent.com/17018444/208839168-95f0b19a-8cae-44db-8d40-b60eab13de7a.png)

**Comment by chenxuuu** [comment]
你需要按rrc demo里的方式来配置216mhz，不是在这里改

**Comment by NgoHungCuong** [comment]
Thank you.
