### ISSUE TITLE
air32_daplink.hex turns off all LEDs on dev board?

### ISSUE THREAD

**Issue by 8fdafs2** [openLuat/luatos-soc-air32f103#2]
The preloaded firmware (DAPLink) enable LEDs on the dev board to indicate system status, but after I flashed [air32_daplink.hex provided by this repo](https://github.com/openLuat/luatos-soc-air32f103/blob/master/AIR_Jlink_Keil/air32_daplink.hex) then all LEDs became consistent off when the board powered on, which confuses me a lot. I'd like to ask if it's the normal situation?

**Comment by chenxuuu** [comment]
目前的固件LED确实不太正常，请等待下一个版本修复
