### ISSUE TITLE
Timer 8, 9, 10, 11, 12, 13, 14 do not working

### ISSUE THREAD

**Issue by NgoHungCuong** [openLuat/luatos-soc-air32f103#3]
Please confirm AIR32F103CCT6 has Timer 8, 9, 10, 11, 12, 13, 14 or does not have?

**Comment by NgoHungCuong** [comment]
[main.zip](https://github.com/openLuat/luatos-soc-air32f103/files/13497943/main.zip)
Please view this source code

**Comment by chenxuuu** [comment]
I tested them, not support
